# Generated by Django 4.2.3 on 2023-08-14 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_advetisements', '0002_alter_advertisements_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertisements',
            options={'managed': False},
        ),
    ]
