# Generated by Django 4.2.3 on 2023-08-14 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_advetisements', '0003_alter_advertisements_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertisements',
            options={},
        ),
    ]
